arb-dir: lib/l10n
template-arb-file: app_ko.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [ko, en, ja, zh]
use-deferred-loading: false
nullable-getter: false
output-dir: lib/generated
synthetic-package: false
untranslated-messages-file: untranslated_messages.txt 